// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUh6IyFEIu7Jbo6nBMvsuxsgoAO9yHS2s',
    appId: '1:532816963272:web:9256b613d7ef0af23067fd',
    messagingSenderId: '532816963272',
    projectId: 'desafio-prouser',
    authDomain: 'desafio-prouser.firebaseapp.com',
    storageBucket: 'desafio-prouser.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgDTJb-WBjo2evrzhehwIZpymDozHo77E',
    appId: '1:532816963272:android:ea57bdbbb3b23b773067fd',
    messagingSenderId: '532816963272',
    projectId: 'desafio-prouser',
    storageBucket: 'desafio-prouser.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaj1ooSuDY08PwjOn4Ngbl2nAX8oZIXxs',
    appId: '1:532816963272:ios:a784e19abd4991d23067fd',
    messagingSenderId: '532816963272',
    projectId: 'desafio-prouser',
    storageBucket: 'desafio-prouser.appspot.com',
    iosClientId: '532816963272-qn0setoetrfdq6c298s5pmobd9gibjq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.desafioProuser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaj1ooSuDY08PwjOn4Ngbl2nAX8oZIXxs',
    appId: '1:532816963272:ios:a784e19abd4991d23067fd',
    messagingSenderId: '532816963272',
    projectId: 'desafio-prouser',
    storageBucket: 'desafio-prouser.appspot.com',
    iosClientId: '532816963272-qn0setoetrfdq6c298s5pmobd9gibjq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.desafioProuser',
  );
}
